apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: java-quarkus-169927775
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: java-quarkus-169927775
    app.kubernetes.io/part-of: test-app-169927775
  name: java-quarkus-169927775
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: java-quarkus-app
      app.kubernetes.io/instance: java-quarkus-169927775
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: java-quarkus-app
        app.kubernetes.io/instance: java-quarkus-169927775
    spec:
      containers:
      - image: quay.io/hacdev/8o8imxhl-tenant/test-app-169927775/java-quarkus-169927775@sha256:363b942c9da572fed08496793c27251c9be234239b0a202338876b3d0e48a3c0
        name: my-java-quarkus
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 100Mi
status: {}
