apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: java-quarkus-169927775
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/hacdev/8o8imxhl-tenant/test-app-169927775/java-quarkus-169927775@sha256:363b942c9da572fed08496793c27251c9be234239b0a202338876b3d0e48a3c0
        name: my-java-quarkus
        resources: {}
status: {}
